---

- name: Remove conflicting packages
  ansible.builtin.package:
    name: "{{ pkg_remove }}"
    state: absent

- name: Install cartography dependencies
  ansible.builtin.package:
    name: "{{ pkg_deps }}"
    state: present

- name: Install cartography
  ansible.builtin.pip:
    name: "{{ cartography_pip }}"
    version: "{{ cartography_version | default(omit) }}"
    state: present

- name: Ensure cartography user exists
  ansible.builtin.user:
    name: "{{ cartography_user }}"
    home: "{{ cartography_home }}"
    system: true

- name: Ensure logs folder exists
  ansible.builtin.file:
    dest: /var/log/cartography
    state: directory
    mode: '0775'
    owner: "{{ cartography_user }}"
