---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when: not is_container | bool

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes
  become_user: root
  when: not is_container | bool
