---
name: default-bare

on:
  push:
  pull_request:
  schedule:  # run weekly, every Thursday 01:00
    - cron: '0 1 * * 4'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.cartography
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.cartography
          [ -f molecule/default/requirements.yml ] && ansible-galaxy install -r molecule/default/requirements.yml
          { echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          set -x
          pwd
          env
          find -ls
      - name: Set java
        run: |
          set -x
          sudo rm -Rf /usr/lib/jvm/temurin-8-jdk-amd64 /usr/lib/jvm/temurin-11-jdk-amd64
          sudo update-java-alternatives --list
          sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep '17-jdk' | cut -d " " -f1)
        continue-on-error: true
      - name: Set java - /etc/environment
        run: |
          set -x
          cat /etc/environment
          sed "s@^JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64@JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64@" /etc/environment | sudo tee /etc/environment
        continue-on-error: true
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.cartography && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/juju4.cartography && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          ansible -i inventory --connection=local -m setup localhost
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status neo4j || true
          systemctl -l --no-pager status cartography || true
          systemctl -l --no-pager status cartography@ || true
          systemctl -l --no-pager status cartography@default || true
          systemctl -l --no-pager status cartography@.timer || true
          systemctl -l --no-pager status cartography@default.timer || true
          systemd-analyze --no-pager security || true
          systemd-analyze --no-pager security cartography@ || true
          systemd-analyze --no-pager verify cartography@ || true
          rsyslogd -v
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - etc
        run: |
          set -x
          cat /etc/neo4j/neo4j.conf
          sudo cat /etc/default/cartography*
          cat /etc/systemd/system/cartography@.service
          cat /etc/systemd/system/cartography@.timer
          cat /lib/systemd/system/neo4j.service
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - run
        run: |
          set -x
          sudo -u _cartography cartography -h
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - cypher
        run: |
          set -x
          echo "CALL db.schema.visualization()" | cypher-shell -a localhost -u neo4j -p neo4j
          echo "MATCH (n) RETURN labels(n), count(*)" | cypher-shell -a localhost -u neo4j -p neo4j
          echo "MATCH ()-[r]->() RETURN count(r) as count" | cypher-shell -a localhost -u neo4j -p neo4j
        if: ${{ always() }}
        continue-on-error: true
